IF EXISTS (SELECT NAME FROM Sysdatabases WHERE NAME = 'QLNV')
DROP DATABASE Quanlynhanvien
CREATE DATABASE Quanlynhanvien
CREATE DATABASE QLNV
USE [master]
DROP DATABASE QuanLyNhanVienDB

ALTER DATABASE Quanlynhanvien
MODIFY NAME = QuanLyNhanVienDB
CREATE DATABASE QuanlynhanvienDB
USE QuanlynhanvienDB


CREATE TABLE NHANVIEN (
	honv NVARCHAR(10) NOT NULL,
	tenlot NVARCHAR(30) NOT NULL,
	tennv NVARCHAR(10) NOT NULL,
	manv INT NOT NULL PRIMARY KEY,
	ngaysinh DATE,
	diachi NVARCHAR(300),
	phai NVARCHAR(10),
	luong MONEY NOT NULL,
	maquanly INT NOT NULL,
	tenphong NVARCHAR(50) NOT NULL,
)

CREATE TABLE PHONGBAN(
	tenphong NVARCHAR(50) NOT NULL,
	maphong  INT NOT NULL PRIMARY KEY,
	truongphong INT NOT NULL,
	ngaynhanchuc DATE NOT NULL,
	
)

CREATE TABLE DIADIEM_PHONG(
	maphong INT NOT NULL FOREIGN KEY REFERENCES PHONGBANG(maphong),
	diadiem NVARCHAR(100) NOT NULL,
	PRIMARY KEY( maphong,diadiem)
)

CREATE TABLE THANNHAN(
	manv INT NOT NULL FOREIGN KEY REFERENCES NHANVIEN(manv),
	tentn NVARCHAR(50) NOT NULL,
	phai NVARCHAR(10) NOT NULL,
	ngaysinh DATE,
	quanhe NVARCHAR(20) NOT NULL,
	PRIMARY KEY(manv,tentn)
)

CREATE TABLE DEAN(
	tenda NVARCHAR(100) NOT NULL,
	mada INT NOT NULL PRIMARY KEY,
	diadiemda NVARCHAR(100) NOT NULL,
	phong INT NOT NULL,
)
CREATE TABLE PHANCONG(
	manv INT NOT NULL FOREIGN KEY REFERENCES NHANVIEN(manv),
	soda INT NOT NULL FOREIGN KEY REFERENCES DEAN(mada),
	sogio INT NOT NULL,
	PRIMARY KEY (manv,soda)	
)
DELETE FROM NHANVIEN
INSERT INTO NHANVIEN

VALUES
	(N'Đinh',N'Bá', N'Tiến',123456789,'1985-01-09',N'731,Trần Hưng Đạo,Q1,TPHCM',N'Nam',3000000,333445555,5)
