CREATE DATABASE QuanLyDoanhNghiepDB
USE QuanLyDoanhNghiepDB


CREATE TABLE LOAISP
(	MaLoaiSP NCHAR(4) NOT NULL PRIMARY KEY,
	TenLoaiSP NVARCHAR(50) NOT NULL
)
CREATE TABLE SANPHAM
(	MaSP NCHAR(5) NOT NULL PRIMARY KEY,
	TenSP NVARCHAR(50) NOT NULL,
	MaLoaiSP NCHAR(4) NOT NULL FOREIGN KEY REFERENCES LOAISP(MaLoaiSP),
	GiaBan MONEY NOT NULL,
	SoLuong INT NOT NULL
)
CREATE TABLE NHANVIEN(
	MaNV NCHAR(5) NOT NULL PRIMARY KEY,
	HoTenNV NVARCHAR(50) NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	QueQuan NVARCHAR(30) NOT NULL,
	Tuoi DATE
)
CREATE TABLE BANHANG(
	MaNV NCHAR(5) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MaNV),
	MaSP NCHAR(5) NOT NULL FOREIGN KEY REFERENCES SANPHAM(MaSP),
	SoLuongDaBan INT NOT NULL,
	PRIMARY KEY (MaNV,MaSP)	
)

-- Cau 1 
INSERT INTO LOAISP	VALUES
	('L001',N'Mỹ phẩm')

INSERT INTO SANPHAM VALUES
	('SP001',N'Kem dưỡng da','L001',210000,100)
--cau 2
SELECT s.TenSP,s.SoLuong FROM SANPHAM s
--cau 3
SELECT b.MaNV,n.HoTenNV,b.MaSP FROM NHANVIEN n,BANHANG b
WHERE n.MaNV=b.MaNV
--cau 4
SELECT n.MaNV,n.HoTenNV,b.MaSP FROM NHANVIEN n
LEFT JOIN BANHANG b ON b.MaNV= n.MaNV
--cau 5
SELECT s.MaSP,s.TenSP,l.MaLoaiSP, l.TenLoaiSP FROM SANPHAM s, LOAISP l
WHERE s.MaLoaiSP=l.MaLoaiSP
-- cau 6
SELECT * FROM NHANVIEN n
WHERE n.MaNV IN (SELECT b.MaNV FROM BANHANG b WHERE b.SoLuongDaBan>=10)
--cau 7
SELECT * FROM SANPHAM s
WHERE s.SoLuong>=20 AND s.TenSP!=N'Kem dưỡng da'
--cau 8 
SELECT * FROM NHANVIEN n
ORDER BY n.QueQuan,n.GioiTinh
-- cau 9
SELECT b.MaNV,s.TenSP, l.TenLoaiSP FROM SANPHAM s,BANHANG b, LOAISP l
WHERE  s.MaSP=b.MaSP AND l.MaLoaiSP=s.MaLoaiSP
-- cau 10
SELECT COUNT(*) AS N'Số lượng nhân viên bán SP001' FROM NHANVIEN n
WHERE n.MaNV IN (SELECT b.MaNV FROM BANHANG b WHERE b.MaSP='SP001')


