
-- câu 1
DROP DATABASE ThueXeDB
CREATE DATABASE ThueXeDB
USE ThueXeDB

CREATE TABLE NHACUNGCAP(
	MaNhaCC CHAR(6) NOT NULL,
	TenNhaCC NVARCHAR(150) NOT NULL,
	DiaChi NVARCHAR(150) NOT NULL,
	SoDT CHAR(11)  NOT NULL,
	MaSoThue CHAR(6) NOT NULL,
	PRIMARY KEY(MaNhaCC)
)
CREATE TABLE LOAIDICHVU(
	MaLoaiDV CHAR(4) NOT NULL PRIMARY KEY,
	TenLoaiDV NVARCHAR(150) NOT NULL,
)
CREATE TABLE MUCPHI(
	MaMP CHAR(4) NOT NULL PRIMARY KEY,
	DonGia MONEY NOT NULL,
	MoTa  NVARCHAR(150) NOT NULL,
)
CREATE TABLE DONGXE(
	DongXe VARCHAR(30) NOT NULL PRIMARY KEY,
	HangXe 	VARCHAR(30) NOT NULL,
	SoChoNgoi INT NOT NULL
)
CREATE TABLE DANGKYCUNGCAP(
	MaDKCC	CHAR(5) NOT NULL PRIMARY KEY,
	MaNhaCC CHAR(6) NOT NULL FOREIGN KEY REFERENCES NHACUNGCAP(MaNhaCC),
	MaLoaiDV CHAR(4) NOT NULL FOREIGN KEY REFERENCES LOAIDICHVU(MaLoaiDV),
	DongXe VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES  DONGXE(DongXe),
	MaMP CHAR(4) NOT NULL FOREIGN KEY REFERENCES MUCPHI(MaMP),
	NgayBatDauCungCap DATE NOT NULL,
	NgayKetThucCungCap DATE,
	SoLuongXeDangKy INT NOT NULL
)

--câu 2

-- câu 3
SELECT DongXe FROM DONGXE WHERE SoChoNgoi>5
-- câu 4
SELECT *FROM NHACUNGCAP
WHERE	MaNhaCC IN (SELECT MaNhaCC FROM DANGKYCUNGCAP WHERE
		( DongXe IN(SELECT DongXe FROM DONGXE WHERE HangXe='Toyota')
		AND MaMP IN(SELECT MaMP FROM	MUCPHI WHERE DonGia=15000))
		OR
		( DongXe IN(SELECT DongXe FROM DONGXE WHERE HangXe='KIA')
		AND MaMP IN(SELECT MaMP FROM	MUCPHI WHERE DonGia=20000))
)
--cau 5
SELECT * FROM DONGXE AS d
WHERE d.HangXe LIKE 'T%' AND  LEN(d.DongXe)=5
-- cau 6
SELECT * FROM NHACUNGCAP 
ORDER BY TenNhaCC ASC,MaSoThue DESC
-- cau 7
SELECT n.TenNhaCC,d.MaNhaCC,COUNT(d.MaNhaCC) AS 'so lan dang ky' FROM DANGKYCUNGCAP d, NHACUNGCAP n
WHERE n.MaNhaCC=d.MaNhaCC
GROUP BY d.MaNhaCC,n.TenNhaCC
-- cau 8
SELECT d.HangXe FROM DONGXE AS d 
GROUP BY d.HangXe
 -- c2 
SELECT DISTINCT D.HangXe  FROM DONGXE AS d
-- cau 9
SELECT d.MaDKCC,l.TenLoaiDV,n.TenNhaCC,m.DonGia,d.DongXe,dx.HangXe,d.NgayBatDauCungCap,
		d.NgayKetThucCungCap,d.SoLuongXeDangKy
  FROM DANGKYCUNGCAP AS d, LOAIDICHVU AS l,NHACUNGCAP AS n,MUCPHI m,DONGXE dx
WHERE l.MaLoaiDV=d.MaLoaiDV AND d.MaNhaCC=n.MaNhaCC and d.DongXe=dx.DongXe AND m.MaMP=d.MaMP
-- cau 11
SELECT * FROM NHACUNGCAP
WHERE MaNhaCC IN ( SELECT d.MaNhaCC FROM DANGKYCUNGCAP d WHERE d.DongXe ='Hiace' OR d.DongXe='Cerato')
-- cau 12
SELECT * FROM NHACUNGCAP n
WHERE n.MaNhaCC NOT IN (SELECT d.MaNhaCC FROM DANGKYCUNGCAP d)
-- cau 13
SELECT * FROM NHACUNGCAP
WHERE MaNhaCC IN ( SELECT d.MaNhaCC FROM DANGKYCUNGCAP d WHERE d.DongXe ='Hiace')
EXCEPT 
SELECT * FROM NHACUNGCAP
WHERE MaNhaCC IN ( SELECT d.MaNhaCC FROM DANGKYCUNGCAP d WHERE  d.DongXe='Cerato')
-- cau 14
SELECT DongXe FROM DANGKYCUNGCAP
WHERE YEAR(NgayBatDauCungCap)=2016
EXCEPT
SELECT DongXe FROM DANGKYCUNGCAP
WHERE YEAR(NgayBatDauCungCap)=2015
-- cau 15
CREATE VIEW demxe_vw 
AS
(SELECT d.dongxe,COUNT(*) AS solandangky FROM DANGKYCUNGCAP AS d 
WHERE YEAR(NgayBatDauCungCap)>2015 AND YEAR(NgayBatDauCungCap)<2020
 GROUP BY DongXe)
SELECT * FROM DONGXE d
WHERE d.DongXe IN (SELECT TOP(1)DongXe FROM demxe_vw ORDER BY solandangky DESC)

-- cách 2
SELECT * FROM DONGXE
WHERE dongxe IN (SELECT Top(1)dongxe FROM DANGKYCUNGCAP 
                 WHERE YEAR(NgayBatDauCungCap)>2015 AND YEAR(NgayBatDauCungCap)<2020 
                 GROUP BY dongxe
                 ORDER BY COUNT(*) DESC)


-- cau 16
SELECT dongxe, SUM (d.SoLuongXeDangKy) AS N'Tổng lượng xe đăng ký'  FROM DANGKYCUNGCAP AS d
WHERE d.MaMP IN (SELECT MaMP FROM MUCPHI WHERE DonGia = 20000)
GROUP BY d.DongXe
-- cau 17
SELECT d.MaNhaCC,d.SoLuongXeDangKy,n.DiaChi FROM DANGKYCUNGCAP AS d,NHACUNGCAP n
WHERE d.MaNhaCC IN (SELECT MaNhaCC FROM NHACUNGCAP AS n WHERE n.DiaChi='hai chau') AND
	d.MaNhaCC IN (SELECT MaNhaCC FROM DANGKYCUNGCAP GROUP BY MaNhaCC HAVING COUNT(*)=1) AND
	n.MaNhaCC=d.MaNhaCC
ORDER BY d.SoLuongXeDangKy DESC
	
	-- dáp án đúng
SELECT d.MaNhaCC,SUM (d.SoLuongXeDangKy) AS N'Số lượng xe đăng ký' ,COUNT(MaNhaCC) AS 'Số lượng xe đăng ký'  FROM DANGKYCUNGCAP AS d
WHERE MaNhaCC IN (SELECT MaNhaCC FROM NHACUNGCAP AS n WHERE n.DiaChi='hai chau')
GROUP BY d.MaNhaCC
HAVING COUNT(*)=1
ORDER BY SUM (d.SoLuongXeDangKy) DESC

-- câu 18
UPDATE DANGKYCUNGCAP
SET
	SoLuongXeDangKy= 20
WHERE 
	dongxe IN ( SELECT dongxe FROM DONGXE WHERE HangXe='Toyota') AND
	NgayKetThucCungCap < '2016-12-30'


-- câu 19
UPDATE MUCPHI
SET
	MoTa = N'được sử dụng nhiều'
WHERE 
	MaMP IN ( SELECT MaMP FROM DANGKYCUNGCAP AS d WHERE YEAR(d.NgayBatDauCungCap)=2016
				 GROUP BY d.MaMP 
	          HAVING COUNT(*)>=5)
	        
-- câu 20

DELETE FROM DANGKYCUNGCAP
WHERE DongXe = N'vios' AND NgayBatDauCungCap> '2015-11-10'