/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FileFactory;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import model.KhachHang;
import model.NhomKhachHang;

/**
 *
 * @author lnmin
 */
public class KhachHangFrameUI extends javax.swing.JFrame {

    /**
     * Creates new form KhachHangFrameUI
     */
    public KhachHangFrameUI() {
        initComponents();
        initOtherComponents();
    }

    private void initOtherComponents() {
        root = new DefaultMutableTreeNode("Công ty đa cấp");
        treeNhom.setModel(new DefaultTreeModel(root));
        dtm = new DefaultTableModel();
        dtm.addColumn("Mã khách hàng");
        dtm.addColumn("Tên khách hàng");
        dtm.addColumn("SĐT khách hàng");
        dtm.addColumn("Email khách hàng");
        tblKhachHang.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spHori = new javax.swing.JSplitPane();
        pnLeft = new javax.swing.JPanel();
        scTree = new javax.swing.JScrollPane();
        treeNhom = new javax.swing.JTree();
        pnLeftNhom = new javax.swing.JPanel();
        pnTenNhom = new javax.swing.JPanel();
        lblTenNhom = new javax.swing.JLabel();
        txtTenNhom = new javax.swing.JTextField();
        pnButtonNhom = new javax.swing.JPanel();
        btnThemNhom = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        spVerti = new javax.swing.JSplitPane();
        pnTop = new javax.swing.JPanel();
        scTable = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        pnBottom = new javax.swing.JPanel();
        pnMa = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        pnTen = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        pnSDT = new javax.swing.JPanel();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        pnEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pnButtonKH = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFileOpen = new javax.swing.JMenuItem();
        mnuFileSave = new javax.swing.JMenuItem();
        mnuFileSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuFileExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spHori.setOneTouchExpandable(true);

        pnLeft.setMinimumSize(new java.awt.Dimension(250, 22));
        pnLeft.setPreferredSize(new java.awt.Dimension(250, 0));
        pnLeft.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Công ty");
        treeNhom.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeNhom.setToolTipText("");
        treeNhom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeNhomMouseClicked(evt);
            }
        });
        scTree.setViewportView(treeNhom);

        pnLeft.add(scTree, java.awt.BorderLayout.CENTER);

        pnLeftNhom.setMinimumSize(new java.awt.Dimension(10, 100));
        pnLeftNhom.setPreferredSize(new java.awt.Dimension(100, 100));
        pnLeftNhom.setLayout(new javax.swing.BoxLayout(pnLeftNhom, javax.swing.BoxLayout.Y_AXIS));

        lblTenNhom.setText("Tên danh sách");
        pnTenNhom.add(lblTenNhom);

        txtTenNhom.setColumns(20);
        pnTenNhom.add(txtTenNhom);

        pnLeftNhom.add(pnTenNhom);

        btnThemNhom.setText("Thêm");
        btnThemNhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhomActionPerformed(evt);
            }
        });
        pnButtonNhom.add(btnThemNhom);

        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnButtonNhom.add(jButton1);

        pnLeftNhom.add(pnButtonNhom);

        pnLeft.add(pnLeftNhom, java.awt.BorderLayout.SOUTH);

        spHori.setLeftComponent(pnLeft);
        pnLeft.getAccessibleContext().setAccessibleParent(spHori);

        pnRight.setLayout(new java.awt.BorderLayout());

        spVerti.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        spVerti.setOneTouchExpandable(true);

        pnTop.setMinimumSize(new java.awt.Dimension(22, 300));
        pnTop.setPreferredSize(new java.awt.Dimension(786, 350));
        pnTop.setLayout(new java.awt.BorderLayout());

        scTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scTable.setToolTipText("");
        scTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        scTable.setViewportView(tblKhachHang);

        pnTop.add(scTable, java.awt.BorderLayout.CENTER);

        spVerti.setTopComponent(pnTop);

        pnBottom.setLayout(new javax.swing.BoxLayout(pnBottom, javax.swing.BoxLayout.Y_AXIS));

        pnMa.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        lblMa.setText("Mã");
        lblMa.setMaximumSize(new java.awt.Dimension(80, 15));
        lblMa.setMinimumSize(new java.awt.Dimension(80, 15));
        lblMa.setPreferredSize(new java.awt.Dimension(90, 15));
        pnMa.add(lblMa);

        txtMa.setColumns(20);
        pnMa.add(txtMa);

        pnBottom.add(pnMa);

        pnTen.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        lblTen.setText("Tên");
        lblTen.setMaximumSize(new java.awt.Dimension(80, 15));
        lblTen.setMinimumSize(new java.awt.Dimension(80, 15));
        lblTen.setPreferredSize(new java.awt.Dimension(90, 15));
        pnTen.add(lblTen);

        txtTen.setColumns(20);
        pnTen.add(txtTen);

        pnBottom.add(pnTen);

        pnSDT.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        lblSDT.setText("Số điện thoại");
        lblSDT.setMaximumSize(new java.awt.Dimension(80, 15));
        lblSDT.setMinimumSize(new java.awt.Dimension(80, 15));
        lblSDT.setPreferredSize(new java.awt.Dimension(90, 15));
        pnSDT.add(lblSDT);

        txtSDT.setColumns(20);
        pnSDT.add(txtSDT);

        pnBottom.add(pnSDT);

        pnEmail.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        lblEmail.setText("Email");
        lblEmail.setMaximumSize(new java.awt.Dimension(80, 15));
        lblEmail.setMinimumSize(new java.awt.Dimension(80, 15));
        lblEmail.setPreferredSize(new java.awt.Dimension(90, 15));
        pnEmail.add(lblEmail);

        txtEmail.setColumns(20);
        pnEmail.add(txtEmail);

        pnBottom.add(pnEmail);

        pnButtonKH.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        btnClear.setText("Làm sạch");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnButtonKH.add(btnClear);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnButtonKH.add(btnThem);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnButtonKH.add(btnXoa);

        pnBottom.add(pnButtonKH);

        spVerti.setRightComponent(pnBottom);

        pnRight.add(spVerti, java.awt.BorderLayout.CENTER);

        spHori.setRightComponent(pnRight);

        getContentPane().add(spHori, java.awt.BorderLayout.CENTER);

        mnuFile.setText("Hệ thống");

        mnuFileOpen.setText("Mở File");
        mnuFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileOpen);

        mnuFileSave.setText("Lưu File");
        mnuFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileSaveActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileSave);
        mnuFile.add(mnuFileSeparator1);

        mnuFileExit.setText("Exit");
        mnuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileExit);

        mnuBar.add(mnuFile);

        setJMenuBar(mnuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearInfoOnTextField();
    }//GEN-LAST:event_btnClearActionPerformed

    private void clearInfoOnTextField() {
        txtMa.setText(null);
        txtTen.setText(null);
        txtSDT.setText(null);
        txtEmail.setText(null);
    }
    private void mnuFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileSaveActionPerformed
        // TODO add your handling code here:
        saveFile();
    }//GEN-LAST:event_mnuFileSaveActionPerformed

    private void mnuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileExitActionPerformed
        // TODO add your handling code here:
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Có chắc chắn thoát không", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);
        if (showConfirmDialog == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuFileExitActionPerformed
    private void showOnTable() {

        nodeSelected = (DefaultMutableTreeNode) treeNhom.getLastSelectedPathComponent();
        if (nodeSelected != null && nodeSelected.getLevel() == 1) {
            nhomSelected = (NhomKhachHang) nodeSelected.getUserObject();
            txtTenNhom.setText(nhomSelected.getTenNhom());
            dtm.setRowCount(0);
            for (KhachHang kh : nhomSelected.getDsKhachHang()) {
                Vector<String> vtkh = new Vector<>();
                vtkh.add(kh.getMa());
                vtkh.add(kh.getTen());
                vtkh.add(kh.getSoDienThoai());
                vtkh.add(kh.getEmail());
                dtm.addRow(vtkh);
            }
        }

    }

    private void saveFile() {
        JFileChooser chooser = new JFileChooser();
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            String luuFile = FileFactory.luuFile(dsNhomKhachHang, selectedFile.getAbsolutePath());
            JOptionPane.showMessageDialog(null, luuFile);
        }
    }
    private void mnuFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileOpenActionPerformed
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = chooser.getSelectedFile();
                dsNhomKhachHang = FileFactory.loadFile(selectedFile.getAbsolutePath());
                showData();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Đọc thất bại");
            }

        }
    }//GEN-LAST:event_mnuFileOpenActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        addKhachHang();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        showOnInfoFrame();
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteKhachHang();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void treeNhomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeNhomMouseClicked
        showOnTable();
    }//GEN-LAST:event_treeNhomMouseClicked

    private void btnThemNhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhomActionPerformed
        // TODO add your handling code here:
        themDanhSach();
    }//GEN-LAST:event_btnThemNhomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        xoaDanhSach();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void xoaDanhSach() {
        dsNhomKhachHang.remove(nhomSelected);
        showData();
    }

    private void themDanhSach() {
        NhomKhachHang nhom = new NhomKhachHang("", txtTenNhom.getText());
        dsNhomKhachHang.add(nhom);
        txtTenNhom.setText(null);
        showData();
    }

    private void addKhachHang() {
        KhachHang kh = new KhachHang(
                txtMa.getText(),
                txtTen.getText(),
                txtSDT.getText(),
                txtEmail.getText());
        nhomSelected.themKhachHang(kh);
        showOnTable();
    }

    private void deleteKhachHang() {
        if (nhomSelected != null && tblKhachHang.getSelectedRow() != -1) {
            nhomSelected.getDsKhachHang().remove(tblKhachHang.getSelectedRow());
            showOnTable();

        }
    }

    private void showOnInfoFrame() {
        int rowSelected = tblKhachHang.getSelectedRow();
        if (rowSelected == -1) {
            return;
        }
        txtMa.setText((String) tblKhachHang.getValueAt(rowSelected, 0));
        txtTen.setText((String) tblKhachHang.getValueAt(rowSelected, 1));
        txtSDT.setText((String) tblKhachHang.getValueAt(rowSelected, 2));
        txtEmail.setText((String) tblKhachHang.getValueAt(rowSelected, 3));
    }

    private void showData() {

        root.removeAllChildren();

        for (NhomKhachHang nhomKhachHang : dsNhomKhachHang) {
            DefaultMutableTreeNode nhom = new DefaultMutableTreeNode(nhomKhachHang);
            root.add(nhom);
        }
        DefaultTreeModel treeModel = (DefaultTreeModel) treeNhom.getModel();

        treeModel.reload(root);
        treeNhom.setModel(treeModel);
        treeNhom.validate();
        treeNhom.repaint();
        treeNhom.expandRow(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHangFrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHangFrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHangFrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHangFrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHangFrameUI().setVisible(true);
            }
        });
    }

    private DefaultTableModel dtm;
    private NhomKhachHang nhomSelected;
    private DefaultMutableTreeNode nodeSelected = null;
    private DefaultMutableTreeNode root = null;
    private Vector<NhomKhachHang> dsNhomKhachHang = new Vector<>();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemNhom;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenNhom;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFileExit;
    private javax.swing.JMenuItem mnuFileOpen;
    private javax.swing.JMenuItem mnuFileSave;
    private javax.swing.JPopupMenu.Separator mnuFileSeparator1;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnButtonKH;
    private javax.swing.JPanel pnButtonNhom;
    private javax.swing.JPanel pnEmail;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLeftNhom;
    private javax.swing.JPanel pnMa;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnSDT;
    private javax.swing.JPanel pnTen;
    private javax.swing.JPanel pnTenNhom;
    private javax.swing.JPanel pnTop;
    private javax.swing.JScrollPane scTable;
    private javax.swing.JScrollPane scTree;
    private javax.swing.JSplitPane spHori;
    private javax.swing.JSplitPane spVerti;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTree treeNhom;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenNhom;
    // End of variables declaration//GEN-END:variables

}
